---

services:

  test:
    build: .
    volumes:
      - .:/src
    command: prove
    environment:
      - PUSHGATEWAY=http://pushgateway:9091
    depends_on:
      pushgateway:
        condition: service_healthy

  test_and_cover:
    build: .
    environment:
      # pass through info needed by coveralls uploader
      - GITHUB_TOKEN
      - GITHUB_RUN_ID
      - GITHUB_EVENT_TOKEN
      - GITHUB_EVENT_PATH
      - GITHUB_SHA
      - GITHUB_REF
      - GITHUB_ACTIONS
      - PUSHGATEWAY=http://pushgateway:9091
    command: cover -test -report Coveralls 
    depends_on:
      pushgateway:
        condition: service_healthy

  pushgateway:
    image: prom/pushgateway
    command:
      - --web.enable-admin-api
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "-O", "/dev/null", "pushgateway:9091/-/healthy" ]
      x-healthcheck-defaults: &healthcheck-defaults
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 5
